### ISSUE TITLE
Object of class class@anonymous could not be converted to string

### ISSUE THREAD

**Issue by artistro08** [mplodowski/seomanager-plugin-public#25]
Object of class class@anonymous could not be converted to string

```
Symfony\Component\Debug\Exception\FatalThrowableError: Object of class class@anonymous could not be converted to string in /home/artistro08/.sites/kicksaas/plugins/renatio/seomanager/components/SeoTags.php:102
Stack trace:
#0 /home/artistro08/.sites/kicksaas/plugins/renatio/seomanager/components/SeoTags.php(102): str_replace()
#1 /home/artistro08/.sites/kicksaas/plugins/renatio/seomanager/components/SeoTags.php(87): Renatio\SeoManager\Components\SeoTags->setOgImageDimensions()
#2 /home/artistro08/.sites/kicksaas/plugins/renatio/seomanager/components/SeoTags.php(31): Renatio\SeoManager\Components\SeoTags->prepareSeoTag()
#3 /home/artistro08/.sites/kicksaas/modules/cms/classes/Controller.php(1266): Renatio\SeoManager\Components\SeoTags->onRender()
#4 /home/artistro08/.sites/kicksaas/modules/cms/twig/Extension.php(155): Cms\Classes\Controller->renderComponent()
#5 /home/artistro08/.sites/kicksaas/storage/cms/twig/8b/8b02ab8162368c147b517f5cb613396028f67e09e8822253e4109078696f6aaa.php(52): Cms\Twig\Extension->componentFunction()
#6 /home/artistro08/.sites/kicksaas/vendor/twig/twig/src/Template.php(405): __TwigTemplate_1c1317f35957037cd2208046ba46d6f085b73c8cf2b433d0f191a5b41a02be80->doDisplay()
#7 /home/artistro08/.sites/kicksaas/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#8 /home/artistro08/.sites/kicksaas/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#9 /home/artistro08/.sites/kicksaas/modules/cms/classes/Controller.php(1122): Twig\Template->render()
#10 /home/artistro08/.sites/kicksaas/modules/cms/twig/Extension.php(115): Cms\Classes\Controller->renderPartial()
#11 /home/artistro08/.sites/kicksaas/storage/cms/twig/b4/b48c0f3dede825f63e96de397aa31c8de116e34919f4189feb0e23fa1cb41c83.php(42): Cms\Twig\Extension->partialFunction()
#12 /home/artistro08/.sites/kicksaas/vendor/twig/twig/src/Template.php(405): __TwigTemplate_107c8a89757e84573852498997cc344d9b798b66267a01885eb76a50c4238087->doDisplay()
#13 /home/artistro08/.sites/kicksaas/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#14 /home/artistro08/.sites/kicksaas/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#15 /home/artistro08/.sites/kicksaas/modules/cms/classes/Controller.php(435): Twig\Template->render()
#16 /home/artistro08/.sites/kicksaas/modules/cms/classes/Controller.php(222): Cms\Classes\Controller->runPage()
#17 /home/artistro08/.sites/kicksaas/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run()
#18 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#19 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#20 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#21 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#22 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#23 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#24 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#26 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#28 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#30 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#32 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#34 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
#36 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#37 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
#38 /home/artistro08/.sites/kicksaas/vendor/october/rain/src/Router/CoreRouter.php(31): Illuminate\Routing\Router->dispatchToRoute()
#39 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch()
#40 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#41 /home/artistro08/.sites/kicksaas/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle()
#43 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /home/artistro08/.sites/kicksaas/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#45 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#46 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#48 /home/artistro08/.sites/kicksaas/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#49 /home/artistro08/.sites/kicksaas/index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#50 /home/artistro08/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('/home/artistro0...')
#51 {main}
```

**To Reproduce**
1. Fresh install of  OCS
2. Install plugin with project:sync
3. add component to 

**Expected behavior**
Plugin working without error, and displays SEO content

**October version**
v2.2.9

**Plugin version**
3.1.2

**Comment by artistro08** [comment]
Turns out it was an issue with using a variable I was setting on the template. Closing this
